language: julia
os:
  - linux
julia:
  - 1.0
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
